some silly stuff
supermileage/UrbanSteeringFirmware pull request #14
Opened 2022-03-19 14:35 UTC by cosparks

Some misc stuff in this pr

• adds timer reset functionality with double click of ignition button
• fixes brake read
• passes bool ref to read_accessories_inputs so we know when to send can message turning off blinkers (this is the silly code)

2022-03-19 17:01 UTC, silviu-toderita requested changes

2022-03-19 17:01 UTC, silviu-toderita commented on src/main.cpp
> +#define ACCESSORIES_TRANSMIT_INTERVAL 0.05f
Excellent!

2022-03-19 17:01 UTC, silviu-toderita commented on src/main.cpp
> +    char brakeVal = (char)brake.read();
I think the brake read needs to be inverted. The button read will be HIGH when the brake is off, and LOW when the brake is on.

2022-03-19 17:37 UTC, cosparks commented on src/main.cpp
> +    char brakeVal = (char)brake.read();
i checked the code in apoorv's pr where he changed brake to PullUp and it's not inverted.  can you confirm with him?

2022-03-22 04:49 UTC, silviu-toderita approved these changes

2022-03-22 04:49 UTC, merged